/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface LcrgCourseCard {}
  interface LcrgProgramGrid {}
  interface LcrgProgramViewer {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLLcrgCourseCardElement extends Components.LcrgCourseCard, HTMLStencilElement {}
  var HTMLLcrgCourseCardElement: {
    prototype: HTMLLcrgCourseCardElement;
    new (): HTMLLcrgCourseCardElement;
  };

  interface HTMLLcrgProgramGridElement extends Components.LcrgProgramGrid, HTMLStencilElement {}
  var HTMLLcrgProgramGridElement: {
    prototype: HTMLLcrgProgramGridElement;
    new (): HTMLLcrgProgramGridElement;
  };

  interface HTMLLcrgProgramViewerElement extends Components.LcrgProgramViewer, HTMLStencilElement {}
  var HTMLLcrgProgramViewerElement: {
    prototype: HTMLLcrgProgramViewerElement;
    new (): HTMLLcrgProgramViewerElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'lcrg-course-card': HTMLLcrgCourseCardElement;
    'lcrg-program-grid': HTMLLcrgProgramGridElement;
    'lcrg-program-viewer': HTMLLcrgProgramViewerElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppProfile {
    'name'?: string;
  }
  interface AppRoot {}
  interface LcrgCourseCard {}
  interface LcrgProgramGrid {}
  interface LcrgProgramViewer {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'lcrg-course-card': LcrgCourseCard;
    'lcrg-program-grid': LcrgProgramGrid;
    'lcrg-program-viewer': LcrgProgramViewer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'lcrg-course-card': LocalJSX.LcrgCourseCard & JSXBase.HTMLAttributes<HTMLLcrgCourseCardElement>;
      'lcrg-program-grid': LocalJSX.LcrgProgramGrid & JSXBase.HTMLAttributes<HTMLLcrgProgramGridElement>;
      'lcrg-program-viewer': LocalJSX.LcrgProgramViewer & JSXBase.HTMLAttributes<HTMLLcrgProgramViewerElement>;
    }
  }
}


